// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Demo.Library.CompiledModels
{
    public partial class FinanceContextModel
    {
        partial void Initialize()
        {
            var credit = CreditEntityType.Create(this);
            var loan = LoanEntityType.Create(this);
            var log = LogEntityType.Create(this);
            var person = PersonEntityType.Create(this);
            var socialSecurity = SocialSecurityEntityType.Create(this);
            var user = UserEntityType.Create(this);

            CreditEntityType.CreateForeignKey1(credit, person);
            LoanEntityType.CreateForeignKey1(loan, person);
            SocialSecurityEntityType.CreateForeignKey1(socialSecurity, person);
            UserEntityType.CreateForeignKey1(user, person);

            CreditEntityType.CreateAnnotations(credit);
            LoanEntityType.CreateAnnotations(loan);
            LogEntityType.CreateAnnotations(log);
            PersonEntityType.CreateAnnotations(person);
            SocialSecurityEntityType.CreateAnnotations(socialSecurity);
            UserEntityType.CreateAnnotations(user);

            AddAnnotation("ProductVersion", "6.0.9");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
