// <auto-generated />
using Demo.Library.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Demo.Library.CompiledModels
{
    [DbContext(typeof(FinanceContext))]
    public partial class FinanceContextModel : RuntimeModel
    {
        static FinanceContextModel()
        {
            var model = new FinanceContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static FinanceContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
